In [96]:
import pandas as pd 
import os
import geopandas as gpd 
import matplotlib.pyplot as plt 
from shapely.geometry import Point 
from shapely.geometry import box
from matplotlib.colors import Normalize
import matplotlib.cm as cm
import matplotlib
import numpy as np

SyntaxError: invalid syntax (109918523.py, line 11)

In [2]:
# Set the working directory
os.chdir('C:/Users/user/Documents/Unibo/Economics and Econometrics/Second Year/First Semester/Introduction to Python for Economists/Project')

nuclear_plants = pd.read_csv('nuclear_power_plants.csv') # data from "https://github.com/cristianst85/GeoNuclearData/blob/master/data/csv/denormalized/nuclear_power_plants.csv"
print(nuclear_plants.head())

# Consider only operational nuclear plants
operational_nuclear_plants = ["Operational"]
nuclear_plants = nuclear_plants[nuclear_plants['Status'].isin(operational_nuclear_plants)]
print(nuclear_plants.head())

   Id                  Name   Latitude  Longitude Country CountryCode  \
0   1                Ågesta  59.206000   18.08290  Sweden          SE
1   2  Akademik Lomonosov-1  69.709579  170.30625  Russia          RU
2   3  Akademik Lomonosov-2  69.709579  170.30625  Russia          RU
3   4              Akhvaz-1        NaN        NaN    Iran          IR
4   5              Akhvaz-2        NaN        NaN    Iran          IR

        Status ReactorType        ReactorModel ConstructionStartAt  \
0     Shutdown        PHWR                 NaN          1957-12-01
1  Operational         PWR  KLT-40S 'Floating'          2007-04-15
2  Operational         PWR  KLT-40S 'Floating'          2007-04-15
3      Planned         NaN                 NaN                 NaN
4      Planned         NaN                 NaN                 NaN

  OperationalFrom OperationalTo  Capacity              LastUpdatedAt  \
0      1964-05-01    1974-06-02       9.0  2015-05-24T04:51:37+03:00
1      2020-05-22           NaN      30.0                 2021-05-31
2      2020-05-22           NaN      30.0                 2021-05-31
3             NaN           NaN       NaN                        NaN
4             NaN           NaN       NaN                        NaN

                 Source  IAEAId
0              WNA/IAEA   528.0
1  WNA/IAEA/Google Maps   895.0
2  WNA/IAEA/Google Maps   896.0
3                   WNA     NaN
4                   WNA     NaN
    Id                  Name   Latitude  Longitude Country CountryCode  \
1    2  Akademik Lomonosov-1  69.709579  170.30625  Russia          RU
2    3  Akademik Lomonosov-2  69.709579  170.30625  Russia          RU
10  11             Almaraz-1  39.807000   -5.69800   Spain          ES
11  12             Almaraz-2  39.807000   -5.69800   Spain          ES
12  13               Angra-1 -23.008000  -44.45700  Brazil          BR

         Status ReactorType        ReactorModel ConstructionStartAt  \
1   Operational         PWR  KLT-40S 'Floating'          2007-04-15
2   Operational         PWR  KLT-40S 'Floating'          2007-04-15
10  Operational         PWR              WH 3LP          1973-07-03
11  Operational         PWR              WH 3LP          1973-07-03
12  Operational         PWR              WH 2LP          1971-05-01

   OperationalFrom OperationalTo  Capacity              LastUpdatedAt  \
1       2020-05-22           NaN      30.0                 2021-05-31
2       2020-05-22           NaN      30.0                 2021-05-31
10      1983-09-01           NaN     900.0  2017-02-10T23:56:15+02:00
11      1984-07-01           NaN     900.0  2019-06-02T20:17:55+03:00
12      1985-01-01           NaN     609.0  2021-02-14T03:47:53+02:00

                  Source  IAEAId
1   WNA/IAEA/Google Maps   895.0
2   WNA/IAEA/Google Maps   896.0
10              WNA/IAEA   153.0
11              WNA/IAEA   154.0
12              WNA/IAEA    24.0

In [34]:
# Filter rows where "OperationalFrom" is NA
na_rows = nuclear_plants[nuclear_plants["OperationalFrom"].isna()]

print("Observations with NA values in 'OperationalFrom':")
print(na_rows)
# Mochovce-3 is now under construction. Thus, we will ignore it 

# Create a vector of EU countries
eu_iso2_codes = [
    "AT", "BE", "BG", "HR", "CY",
    "CZ", "DK", "EE", "FI", "FR",
    "DE", "GR", "HU", "IE", "IT",
    "LV", "LT", "LU", "MT", "NL",
    "PL", "PT", "RO", "SK", "SI",
    "ES", "SE"
]

# Filter for EU countries
nuclear_plants = nuclear_plants[nuclear_plants['CountryCode'].isin(eu_iso2_codes)]

# Convert the operational and decommission dates to datetime
nuclear_plants['OperationalFrom'] = pd.to_datetime(nuclear_plants['OperationalFrom'])
nuclear_plants['OperationalTo'] = pd.to_datetime(nuclear_plants['OperationalTo'])

# Check for null or missing values in the dates
print(nuclear_plants[['OperationalFrom', 'OperationalTo']].isnull().sum())

# Drop 
nuclear_plants.dropna(subset=["OperationalFrom"], inplace=True)

Observations with NA values in 'OperationalFrom':
Empty DataFrame
Columns: [Id, Name, Latitude, Longitude, Country, CountryCode, Status, ReactorType, ReactorModel, ConstructionStartAt, OperationalFrom, OperationalTo, Capacity, LastUpdatedAt, Source, IAEAId]
Index: []
OperationalFrom     0
OperationalTo      99
dtype: int64

In [4]:
# Load the shapefile
sp_path = "NUTS_RG_01M_2021_4326_LEVL_3/NUTS_RG_01M_2021_4326_LEVL_3_repaired.shp"  
eu_map = gpd.read_file(sp_path)

# Define the bounding box for continental Europe
bounding_box = {
    "minx": -10,  # Western limit
    "maxx": 30,   # Eastern limit
    "miny": 35,   # Southern limit
    "maxy": 70    # Northern limit
}
print(eu_map)
print(eu_map.crs)# Filter rows where "CNTR_CODE" is "RO"
ro_observations = eu_map[eu_map["CNTR_CODE"] == "RO"]

# Display the result
print(ro_observations)
print(eu_map.columns)

# Filter for EU countries
eu_map = eu_map[eu_map['CNTR_CODE'].isin(eu_iso2_codes)]


# Create a bounding box as a shapely object
bounding_polygon = box(bounding_box["minx"], bounding_box["miny"], bounding_box["maxx"], bounding_box["maxy"])

# Clip the map using the bounding box
eu_map = eu_map.clip(bounding_polygon)

     NUTS_ID  LEVL_CODE CNTR_CODE                            NAME_LATN  \
0      NO0B2          3        NO                             Svalbard
1      NO0B1          3        NO                 Jan Mayen\r\n   \r\n
2      HR064          3        HR          Krapinsko-zagorska upanija
3      DE21A          3        DE                               Erding
4      DE94E          3        DE                 Osnabrück, Landkreis
...      ...        ...       ...                                  ...
1509   UKM73          3        UK          East Lothian and Midlothian
1510   UKM75          3        UK                   Edinburgh, City of
1511   UKM76          3        UK                              Falkirk
1512   UKM78          3        UK                         West Lothian
1513   UKK24          3        UK  Bournemouth, Christchurch and Poole

                                NUTS_NAME  MOUNT_TYPE  URBN_TYPE  COAST_TYPE  \
0                                Svalbard         3.0        3.0           1
1                    Jan Mayen\r\n   \r\n         NaN        NaN           1
2             Krapinsko-zagorska upanija         4.0        3.0           3
3                                  Erding         4.0        3.0           3
4                    Osnabrück, Landkreis         4.0        2.0           3
...                                   ...         ...        ...         ...
1509          East Lothian and Midlothian         4.0        1.0           1
1510                   Edinburgh, City of         4.0        1.0           1
1511                              Falkirk         4.0        1.0           1
1512                         West Lothian         4.0        1.0           1
1513  Bournemouth, Christchurch and Poole         4.0        1.0           1

        FID                                           geometry
0     NO0B2  MULTIPOLYGON (((33.09131 80.24908, 33.09929 80...
1     NO0B1  POLYGON ((-7.96242 71.16199, -7.9553 71.15968,...
2     HR064  POLYGON ((16.25128 46.07165, 16.24254 46.0622,...
3     DE21A  POLYGON ((12.01712 48.43068, 12.0221 48.42585,...
4     DE94E  POLYGON ((8.01815 52.68391, 8.03442 52.67338, ...
...     ...                                                ...
1509  UKM73  MULTIPOLYGON (((-2.36662 55.94611, -2.36697 55...
1510  UKM75  MULTIPOLYGON (((-3.07764 55.9469, -3.08167 55....
1511  UKM76  POLYGON ((-3.51572 56.00226, -3.51251 55.99411...
1512  UKM78  POLYGON ((-3.42533 55.99403, -3.42699 55.9905,...
1513  UKK24  POLYGON ((-1.80428 50.79602, -1.8025 50.79206,...

[1514 rows x 10 columns]
EPSG:4326
     NUTS_ID  LEVL_CODE CNTR_CODE        NAME_LATN        NUTS_NAME  \
918    RO122          3        RO           Brasov           Brasov
1105   RO424          3        RO            Timis            Timis
1118   RO317          3        RO        Teleorman        Teleorman
1136   RO123          3        RO          Covasna          Covasna
1137   RO216          3        RO           Vaslui           Vaslui
1139   RO221          3        RO           Braila           Braila
1140   RO316          3        RO          Prahova          Prahova
1144   RO321          3        RO        Bucuresti        Bucuresti
1235   RO421          3        RO             Arad             Arad
1236   RO422          3        RO    Caras-Severin    Caras-Severin
1242   RO423          3        RO        Hunedoara        Hunedoara
1243   RO116          3        RO            Salaj            Salaj
1277   RO412          3        RO             Gorj             Gorj
1280   RO124          3        RO         Harghita         Harghita
1290   RO214          3        RO            Neamt            Neamt
1295   RO114          3        RO        Maramures        Maramures
1296   RO115          3        RO        Satu Mare        Satu Mare
1297   RO215          3        RO          Suceava          Suceava
1305   RO322          3        RO            Ilfov            Ilfov
1306   RO411          3        RO             Dolj             Dolj
1329   RO121          3        RO             Alba             Alba
1333   RO222          3        RO            Buzau            Buzau
1336   RO223          3        RO        Constanta        Constanta
1346   RO113          3        RO             Cluj             Cluj
1360   RO224          3        RO           Galati           Galati
1361   RO225          3        RO           Tulcea           Tulcea
1383   RO213          3        RO             Iasi             Iasi
1384   RO111          3        RO            Bihor            Bihor
1385   RO226          3        RO          Vrancea          Vrancea
1389   RO314          3        RO          Giurgiu          Giurgiu
1390   RO311          3        RO            Arges            Arges
1393   RO211          3        RO            Bacau            Bacau
1395   RO315          3        RO         Ialomita         Ialomita
1396   RO125          3        RO            Mures            Mures
1401   RO126          3        RO            Sibiu            Sibiu
1404   RO414          3        RO              Olt              Olt
1408   RO413          3        RO        Mehedinti        Mehedinti
1411   RO415          3        RO           Vâlcea           Vâlcea
1414   RO212          3        RO         Botosani         Botosani
1416   RO112          3        RO  Bistrita-Nasaud  Bistrita-Nasaud
1437   RO312          3        RO         Calarasi         Calarasi
1448   RO313          3        RO        Dâmbovita        Dâmbovita

      MOUNT_TYPE  URBN_TYPE  COAST_TYPE    FID  \
918          3.0        2.0           3  RO122
1105         4.0        2.0           3  RO424
1118         4.0        3.0           3  RO317
1136         3.0        3.0           3  RO123
1137         4.0        3.0           3  RO216
1139         4.0        2.0           3  RO221
1140         2.0        2.0           3  RO316
1144         4.0        1.0           3  RO321
1235         4.0        2.0           3  RO421
1236         2.0        3.0           3  RO422
1242         3.0        2.0           3  RO423
1243         4.0        3.0           3  RO116
1277         4.0        3.0           3  RO412
1280         3.0        3.0           3  RO124
1290         2.0        3.0           3  RO214
1295         3.0        3.0           3  RO114
1296         4.0        3.0           3  RO115
1297         2.0        3.0           3  RO215
1305         4.0        1.0           3  RO322
1306         4.0        2.0           3  RO411
1329         2.0        3.0           3  RO121
1333         4.0        3.0           3  RO222
1336         4.0        2.0           1  RO223
1346         3.0        2.0           3  RO113
1360         4.0        2.0           3  RO224
1361         4.0        3.0           1  RO225
1383         4.0        2.0           3  RO213
1384         4.0        3.0           3  RO111
1385         2.0        3.0           3  RO226
1389         4.0        3.0           3  RO314
1390         4.0        3.0           3  RO311
1393         2.0        3.0           3  RO211
1395         4.0        3.0           3  RO315
1396         4.0        3.0           3  RO125
1401         4.0        2.0           3  RO126
1404         4.0        3.0           3  RO414
1408         4.0        3.0           3  RO413
1411         2.0        3.0           3  RO415
1414         4.0        3.0           3  RO212
1416         3.0        3.0           3  RO112
1437         4.0        3.0           3  RO312
1448         4.0        3.0           3  RO313

                                               geometry
918   POLYGON ((25.45124 46.10409, 25.45145 46.10247...
1105  POLYGON ((20.7053 46.16094, 20.71572 46.15979,...
1118  POLYGON ((25.48049 44.452, 25.4832 44.44953, 2...
1136  POLYGON ((26.26344 46.24634, 26.28676 46.24514...
1137  POLYGON ((28.11381 46.83841, 28.11546 46.82134...
1139  POLYGON ((28.03052 45.40433, 28.02876 45.40046...
1140  POLYGON ((26.07272 45.50579, 26.08637 45.49476...
1144  POLYGON ((26.10446 44.53954, 26.10555 44.51837...
1235  POLYGON ((22.67658 46.40582, 22.67594 46.3955,...
1236  POLYGON ((22.42648 45.66888, 22.44577 45.66053...
1242  POLYGON ((23.59727 45.47347, 23.5939 45.46112,...
1243  POLYGON ((23.84138 47.34001, 23.84057 47.32749...
1277  POLYGON ((23.7805 44.71399, 23.74751 44.71639,...
1280  POLYGON ((25.66158 47.09165, 25.66614 47.08867...
1290  POLYGON ((26.50779 47.27169, 26.53362 47.2524,...
1295  MULTIPOLYGON (((24.9471 47.72912, 24.94765 47....
1296  POLYGON ((23.4936 47.96781, 23.51078 47.95538,...
1297  POLYGON ((26.70057 47.47171, 26.6945 47.46023,...
1305  POLYGON ((26.30182 44.76888, 26.34856 44.73179...
1306  POLYGON ((23.9282 44.53022, 23.92582 44.52886,...
1329  MULTIPOLYGON (((22.81195 46.56886, 22.81315 46...
1333  POLYGON ((26.3921 45.80239, 26.41013 45.79065,...
1336  MULTIPOLYGON (((28.99408 44.67962, 28.98553 44...
1346  MULTIPOLYGON (((24.02272 47.36195, 24.01825 47...
1360  POLYGON ((28.1158 46.10783, 28.11757 46.1067, ...
1361  MULTIPOLYGON (((28.99408 44.67962, 28.98636 44...
1383  MULTIPOLYGON (((28.11381 46.83841, 28.10172 46...
1384  POLYGON ((22.61268 47.33474, 22.60704 47.32809...
1385  POLYGON ((27.49282 46.15921, 27.48662 46.15266...
1389  POLYGON ((25.89074 44.54095, 25.9026 44.5292, ...
1390  POLYGON ((25.32158 45.38109, 25.31683 45.37102...
1393  POLYGON ((27.20622 46.76985, 27.21194 46.76121...
1395  POLYGON ((27.20346 44.78707, 27.2224 44.78254,...
1396  POLYGON ((25.24671 47.09792, 25.236 47.0872, 2...
1401  POLYGON ((24.94655 46.07911, 24.95008 46.07124...
1404  POLYGON ((24.43812 44.84538, 24.4223 44.82639,...
1408  POLYGON ((22.65663 45.10817, 22.67238 45.10158...
1411  POLYGON ((24.52313 45.58056, 24.5305 45.57075,...
1414  POLYGON ((27.39117 47.5894, 27.38382 47.58552,...
1416  POLYGON ((24.96084 47.59685, 24.99049 47.58574...
1437  POLYGON ((28.01737 44.34025, 28.01172 44.32242...
1448  POLYGON ((25.97074 44.71041, 25.97646 44.70128...
Index(['NUTS_ID', 'LEVL_CODE', 'CNTR_CODE', 'NAME_LATN', 'NUTS_NAME',
       'MOUNT_TYPE', 'URBN_TYPE', 'COAST_TYPE', 'FID', 'geometry'],
      dtype='object')

In [5]:
# Create a GeoDataFrame for nuclear plants
plants_gdf = gpd.GeoDataFrame(
    nuclear_plants, geometry=gpd.points_from_xy(nuclear_plants.Longitude, nuclear_plants.Latitude), crs="EPSG:4326"
)
print(plants_gdf.crs)

EPSG:4326

In [36]:
# Load the file into a pandas DataFrame
gdp = pd.read_csv("estat_nama_10r_3gdp.tsv.gz", sep="\t", compression="gzip") # GDP per capita regional

# Split the combined column into separate columns
gdp_split = gdp['freq,unit,geo\\TIME_PERIOD'].str.split(',', expand=True)

# Assign meaningful names to the new columns
gdp_split.columns = ['freq', 'unit', 'geo']

# Merge the split columns back into the original DataFrame
gdp = pd.concat([gdp, gdp_split], axis=1)

# Drop the original combined column (optional)
gdp.drop(columns=['freq,unit,geo\\TIME_PERIOD'], inplace=True)

# Filter the dataset to include only rows where "geo" starts with an allowed prefix
gdp_filtered = gdp[gdp['geo'].str[:2].isin(eu_iso2_codes)]

# Step 1: Filter 'gdp' to keep only relevant rows
relevant_gdp = gdp[gdp['geo'].isin(eu_map['NUTS_ID'])]

# Step 2: Merge the filtered 'gdp' with 'eu_map'
merged = eu_map.merge(relevant_gdp, left_on="NUTS_ID", right_on="geo", how="right")

print(merged)

     NUTS_ID  LEVL_CODE CNTR_CODE                NAME_LATN  \
0      AT111          3        AT         Mittelburgenland
1      AT112          3        AT           Nordburgenland
2      AT113          3        AT            Südburgenland
3      AT121          3        AT  Mostviertel-Eisenwurzen
4      AT122          3        AT     Niederösterreich-Süd
...      ...        ...       ...                      ...
7688   SK023          3        SK          Nitriansky kraj
7689   SK031          3        SK            ilinský kraj
7690   SK032          3        SK     Banskobystrický kraj
7691   SK041          3        SK           Preovský kraj
7692   SK042          3        SK             Koický kraj

                    NUTS_NAME  MOUNT_TYPE  URBN_TYPE  COAST_TYPE    FID  \
0            Mittelburgenland         4.0        3.0           3  AT111
1              Nordburgenland         4.0        3.0           3  AT112
2               Südburgenland         4.0        3.0           3  AT113
3     Mostviertel-Eisenwurzen         2.0        3.0           3  AT121
4        Niederösterreich-Süd         3.0        2.0           3  AT122
...                       ...         ...        ...         ...    ...
7688          Nitriansky kraj         4.0        2.0           3  SK023
7689            ilinský kraj         3.0        2.0           3  SK031
7690     Banskobystrický kraj         3.0        3.0           3  SK032
7691           Preovský kraj         3.0        3.0           3  SK041
7692             Koický kraj         2.0        2.0           3  SK042

                                               geometry  ...   2016    2017   \
0     POLYGON ((16.63552 47.44531, 16.62806 47.44207...  ...  24500   26500
1     POLYGON ((17.13656 47.9951, 17.09466 47.97087,...  ...  31500   32400
2     POLYGON ((16.44414 47.34632, 16.44847 47.33988...  ...  25700   27000
3     POLYGON ((15.51229 48.3102, 15.52049 48.31099,...  ...  31700   33900
4     POLYGON ((15.93363 48.07037, 15.94567 48.06833...  ...  29500   30800
...                                                 ...  ...     ...     ...
7688  POLYGON ((18.48865 48.54371, 18.49339 48.53502...  ...     62      60
7689  POLYGON ((19.47421 49.60408, 19.46944 49.5964,...  ...     64      61
7690  POLYGON ((19.99554 48.90483, 20.01669 48.90102...  ...     52      51
7691  POLYGON ((21.40376 49.43197, 21.40906 49.42539...  ...     44      42
7692  MULTIPOLYGON (((22.37915 48.83927, 22.37678 48...  ...     57      59

       2018    2019    2020    2021  2022  freq               unit    geo
0     26600   27000   27000   28300     :     A            EUR_HAB  AT111
1     33300   34200   33100   34800     :     A            EUR_HAB  AT112
2     27700   28400   27000   28700     :     A            EUR_HAB  AT113
3     34400   35600   34100   35600     :     A            EUR_HAB  AT121
4     32100   33100   31500   32600     :     A            EUR_HAB  AT122
...      ...     ...     ...     ...   ...  ...                ...    ...
7688     57      60      64      61   59 e    A  PPS_HAB_EU27_2020  SK023
7689     60      63      65      64   64 e    A  PPS_HAB_EU27_2020  SK031
7690     51      51      53      56   57 e    A  PPS_HAB_EU27_2020  SK032
7691     45      43      45      45   44 e    A  PPS_HAB_EU27_2020  SK041
7692     57      56      61      62   60 e    A  PPS_HAB_EU27_2020  SK042

[7693 rows x 36 columns]

In [11]:
years = ["2000", "2001", "2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015",
        "2016", "2017", "2018","2019","2020","2021","2022",]  # List of year columns as strings

# Strip any leading or trailing whitespace from column names
merged.columns = merged.columns.str.strip()

# Filters the years list to include only those that exist as column names in the merged DataFrame.
years = [year for year in years if year in merged.columns]

for year in years:
    # Clean non-numeric characters and spaces
    merged[year] = merged[year].astype(str).str.strip()
    merged[year] = merged[year].str.replace(r"[^\d.]", "", regex=True)  # Keep only numbers and decimal points
    
    # Convert to numeric and fill missing values with 0 (or another default value if preferred)
    merged[year] = pd.to_numeric(merged[year], errors="coerce").fillna(0)

merged_long = pd.melt(
    merged,
    id_vars=["NUTS_ID", "geometry"],  # Keep these as identifiers
    value_vars=years,                # Only melt the year columns
    var_name="TIME_PERIOD",          # Column for years
    value_name="GDP"                 # Column for GDP values
)

# Check for missing values
print(merged_long['GDP'].isna().sum())

We now use 2SLS/FE method to analyse whether there is a correlation between the presence of Nuclear Plants and GDB and other economic variables. The analysis will be performed locally, that is, withing NUTS3 regions of EU.
First, we create a dateset for the analysis. We "fix" up the "nuclear_plants" dataset before merging it with "merged_long":

In [42]:
# Create a function to check operational status
def is_operational(row, year):
    return (row['OperationalFrom'].year <= year) and (pd.isnull(row['OperationalTo']) or row['OperationalTo'].year >= year)

# Generalize: Create a binary variable for each year in the GDP dataset
years = range(2000, 2022)  # Adjust the range based on your GDP dataset
for year in years:
    nuclear_plants[f'is_operational_{year}'] = nuclear_plants.apply(lambda row: is_operational(row, year), axis=1)

print(nuclear_plants.columns)

Index(['Id', 'Name', 'Latitude', 'Longitude', 'Country', 'CountryCode',
       'Status', 'ReactorType', 'ReactorModel', 'ConstructionStartAt',
       'OperationalFrom', 'OperationalTo', 'Capacity', 'LastUpdatedAt',
       'Source', 'IAEAId', 'is_operational_2005', 'is_operational_2000',
       'is_operational_2001', 'is_operational_2002', 'is_operational_2003',
       'is_operational_2004', 'is_operational_2006', 'is_operational_2007',
       'is_operational_2008', 'is_operational_2009', 'is_operational_2010',
       'is_operational_2011', 'is_operational_2012', 'is_operational_2013',
       'is_operational_2014', 'is_operational_2015', 'is_operational_2016',
       'is_operational_2017', 'is_operational_2018', 'is_operational_2019',
       'is_operational_2020', 'is_operational_2021'],
      dtype='object')

In [74]:
filtered_df = nuclear_plants[nuclear_plants["is_operational_2000"]][["OperationalFrom", "is_operational_2000"]]

print(filtered_df)

    OperationalFrom  is_operational_2000
10       1983-09-01                 True
11       1984-07-01                 True
21       1984-12-10                 True
22       1986-03-31                 True
43       1988-06-01                 True
..              ...                  ...
704      1980-12-01                 True
705      1981-05-11                 True
706      1981-11-01                 True
707      1988-08-06                 True
717      1988-03-08                 True

[93 rows x 2 columns]

In [ ]:
# Reshape the operational data to long format for merging
operational_long = nuclear_plants.melt(
    id_vars=['region_identifier'],  # Replace with the column identifying the region
    value_vars=[f'is_operational_{year}' for year in years],
    var_name='year',
    value_name='plant_operational'
)

# Extract year as an integer from the column name
operational_long['year'] = operational_long['year'].str.extract(r'(\d+)').astype(int)

# Merge with the GDP dataset
merged_long = pd.merge(merged_long, operational_long, on=['region_identifier', 'year'], how='left')

# Fill missing values in the plant_operational column with 0 (no plant in operation)
merged_long['plant_operational'] = merged_long['plant_operational'].fillna(0).astype(int)

In [115]:
a = pd.read_csv('API_NY.GDP.MKTP.CD_DS2_en_csv_v2_2.csv')

In [117]:
print(a)

    Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023",
0    Aruba,"ABW","GDP (current US$)","NY.GDP.MKTP.C...
1    Africa Eastern and Southern,"AFE","GDP (curren...
2    Afghanistan,"AFG","GDP (current US$)","NY.GDP....
3    Africa Western and Central,"AFW","GDP (current...
4    Angola,"AGO","GDP (current US$)","NY.GDP.MKTP....
..                                                 ...
261  Kosovo,"XKX","GDP (current US$)","NY.GDP.MKTP....
262  Yemen, Rep.,"YEM","GDP (current US$)","NY.GDP....
263  South Africa,"ZAF","GDP (current US$)","NY.GDP...
264  Zambia,"ZMB","GDP (current US$)","NY.GDP.MKTP....
265  Zimbabwe,"ZWE","GDP (current US$)","NY.GDP.MKT...

[266 rows x 1 columns]

In [ ]:
There is a big problem. The dataset with nuclear plants have a NUTS1 code for each obvservation. While, in the dataset "merged", the one that contains gdp values in long format, the region identifier is NUTS3 code. How can I merge these two different dataset not having the same region identifier? Maybe I can associate nuclear plants to ISO 3 codes from the shapefile. I can use shapefile to delimitate nuclear plants in certain regions identified by NUTS3 codes.